"""initial_schema

Revision ID: b1fdaef0bc6a
Revises: 
Create Date: 2026-01-26 11:38:27.504277

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b1fdaef0bc6a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('type', sa.Enum('SUPERVISED', 'PREFERENCE', name='datasettype'), nullable=False),
    sa.Column('filter_query', sa.JSON(), nullable=True),
    sa.Column('sample_count', sa.Integer(), nullable=False),
    sa.Column('export_path', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_datasets_deleted_at'), 'datasets', ['deleted_at'], unique=False)
    op.create_table('generation_jobs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('adapter_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('QUEUED', 'PROCESSING', 'COMPLETED', 'FAILED', 'CANCELLED', name='jobstatus'), nullable=False),
    sa.Column('progress', sa.Float(), nullable=False),
    sa.Column('num_samples', sa.Integer(), nullable=False),
    sa.Column('audio_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_generation_jobs_deleted_at'), 'generation_jobs', ['deleted_at'], unique=False)
    op.create_table('prompts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('attributes', sa.JSON(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('base_model', sa.String(length=200), nullable=False),
    sa.Column('storage_path', sa.String(length=500), nullable=True),
    sa.Column('training_dataset_id', sa.UUID(), nullable=True),
    sa.Column('training_config', sa.JSON(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_version', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['training_dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sqlite_autoincrement=True
    )
    op.create_index(op.f('ix_adapters_deleted_at'), 'adapters', ['deleted_at'], unique=False)
    op.create_table('experiments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('dataset_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'RUNNING', 'COMPLETED', 'FAILED', 'ARCHIVED', name='experimentstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('best_run_id', sa.UUID(), nullable=True),
    sa.Column('best_loss', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_tests',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('adapter_a_id', sa.UUID(), nullable=True),
    sa.Column('adapter_b_id', sa.UUID(), nullable=True),
    sa.Column('status', sa.Enum('DRAFT', 'GENERATING', 'ACTIVE', 'COMPLETED', name='abteststatus'), nullable=False),
    sa.Column('prompt_ids', postgresql.ARRAY(sa.UUID()), nullable=True),
    sa.Column('results', sa.JSON(), nullable=True),
    sa.Column('total_pairs', sa.Integer(), nullable=True),
    sa.Column('completed_pairs', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adapter_a_id'], ['adapters.id'], ),
    sa.ForeignKeyConstraint(['adapter_b_id'], ['adapters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adapter_versions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('adapter_id', sa.UUID(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weights_path', sa.String(length=500), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adapter_id'], ['adapters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audio_samples',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('adapter_id', sa.UUID(), nullable=True),
    sa.Column('storage_path', sa.String(length=500), nullable=False),
    sa.Column('duration_seconds', sa.Float(), nullable=False),
    sa.Column('sample_rate', sa.Integer(), nullable=False),
    sa.Column('generation_params', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adapter_id'], ['adapters.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiment_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('experiment_id', sa.UUID(), nullable=False),
    sa.Column('adapter_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'RUNNING', 'COMPLETED', 'FAILED', 'CANCELLED', name='runstatus'), nullable=False),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('final_loss', sa.Float(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['adapter_id'], ['adapters.id'], ),
    sa.ForeignKeyConstraint(['experiment_id'], ['experiments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ab_test_pairs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('ab_test_id', sa.UUID(), nullable=False),
    sa.Column('prompt_id', sa.UUID(), nullable=False),
    sa.Column('audio_a_id', sa.UUID(), nullable=True),
    sa.Column('audio_b_id', sa.UUID(), nullable=True),
    sa.Column('job_a_id', sa.UUID(), nullable=True),
    sa.Column('job_b_id', sa.UUID(), nullable=True),
    sa.Column('preference', sa.String(length=10), nullable=True),
    sa.Column('voted_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['ab_test_id'], ['ab_tests.id'], ),
    sa.ForeignKeyConstraint(['audio_a_id'], ['audio_samples.id'], ),
    sa.ForeignKeyConstraint(['audio_b_id'], ['audio_samples.id'], ),
    sa.ForeignKeyConstraint(['job_a_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['job_b_id'], ['generation_jobs.id'], ),
    sa.ForeignKeyConstraint(['prompt_id'], ['prompts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('feedback',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('audio_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('rating_criterion', sa.String(length=50), nullable=True),
    sa.Column('preferred_over', sa.UUID(), nullable=True),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['audio_id'], ['audio_samples.id'], ),
    sa.ForeignKeyConstraint(['preferred_over'], ['audio_samples.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('feedback')
    op.drop_table('ab_test_pairs')
    op.drop_table('experiment_runs')
    op.drop_table('audio_samples')
    op.drop_table('adapter_versions')
    op.drop_table('ab_tests')
    op.drop_table('experiments')
    op.drop_index(op.f('ix_adapters_deleted_at'), table_name='adapters')
    op.drop_table('adapters')
    op.drop_table('prompts')
    op.drop_index(op.f('ix_generation_jobs_deleted_at'), table_name='generation_jobs')
    op.drop_table('generation_jobs')
    op.drop_index(op.f('ix_datasets_deleted_at'), table_name='datasets')
    op.drop_table('datasets')
    # ### end Alembic commands ###
